# Generated by Django 5.0.3 on 2024-12-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/slides', verbose_name='profile avatar')),
                ('link', models.URLField(blank=True, max_length=300, null=True, verbose_name='Web Link')),
            ],
        ),
    ]
