# Generated by Django 5.0.3 on 2024-12-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
