# Generated by Django 5.0.3 on 2024-12-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide_module', '0002_slide_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
