# Generated by Django 5.0.3 on 2024-12-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(blank=True, max_length=300, null=True)),
                ('software_description', models.TextField(blank=True, null=True)),
                ('apk_download', models.FileField(upload_to='apk_file')),
            ],
        ),
    ]
