# Generated by Django 5.0.3 on 2024-12-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
    ]
