# Generated by Django 5.0.3 on 2024-12-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='عنوان تفأل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='متن')),
            ],
        ),
    ]
