# Generated by Django 5.0.3 on 2024-12-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horoscope',
            options={'verbose_name': 'جدول فال ها'},
        ),
    ]
