# Generated by Django 5.0.3 on 2024-12-11 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope_module', '0002_alter_horoscope_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horoscope',
            options={'verbose_name': 'جدول فال ها', 'verbose_name_plural': 'فال ها'},
        ),
    ]
