# Generated by Django 5.0.3 on 2024-11-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
