# Generated by Django 5.0.3 on 2024-11-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_module', '0002_memory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='status',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
