# Generated by Django 5.0.3 on 2024-12-09 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory_module', '0006_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='created_at',
        ),
    ]
