# Generated by Django 5.0.3 on 2024-12-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_module', '0007_remove_bookmark_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='voice_data/'),
        ),
    ]
