# Generated by Django 5.0.3 on 2024-12-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_remove_user_email_remove_user_email_active_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Rating',
            field=models.FloatField(default=0.0),
        ),
    ]
