# Generated by Django 5.0.3 on 2024-12-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_user_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Rating',
            new_name='Content_Rating',
        ),
        migrations.AddField(
            model_name='user',
            name='Total_Rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='View_Rating',
            field=models.FloatField(default=0.0),
        ),
    ]
