# Generated by Django 5.0.3 on 2024-12-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_rename_rating_user_content_rating_user_total_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='First_login',
            field=models.BooleanField(default=False),
        ),
    ]
