# Generated by Django 5.0.3 on 2024-12-10 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/subcategories_images')),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='title')),
                ('video_link', models.URLField(blank=True, max_length=300, null=True, verbose_name='video link')),
                ('image', models.ImageField(upload_to='images/videos_images', verbose_name='image')),
                ('video_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_module.videocategory')),
            ],
        ),
    ]
