# Generated by Django 5.0.3 on 2024-12-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='title'),
        ),
    ]
